name: scripture_card_generator
description: A web app that uses AngularDart Components
version: 0.0.1
homepage: https://tsteward.github.io/scripture-card-generator/
author: Timothy Steward <tsteward0@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  esv_api: ^0.1.2
  pdf: ^1.3.4

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
